mysql-1:
  image: percona:5.7
  command: --server-id=1
    --log-bin=mysql-bin
    --max-binlog-size=4096
    --binlog-format=ROW
    --sync-binlog=1
    --log-slave-updates=ON
    --gtid-mode=ON
    --enforce-gtid-consistency=ON
    --character-set-server=utf8mb4
    --collation-server=utf8mb4_unicode_ci
    --max-connections=1000
    --read-only=OFF
    --binlog-rows-query-log-events=ON
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  volumes:
    - /var/lib/mysql
  ports:
    - "29291:3306"

email:
  image: email:v1
  links:
    - "mysql-1"
  ports:
    - "8001:8001"

text:
  image: text:v1
  links:
    - "mysql-1"
  ports:
    - "8002:8002"

auth:
  image: auth:v1
  links:
    - "mysql-1"
  ports:
    - "8080:8080"

client:
  image: client:v1
  links:
    - "auth"
    - "email"
    - "text"
  ports:
   - "3000:3000"
